package:
    name: payu
    version: {{ GIT_DESCRIBE_TAG }}

build:
    noarch: python
    number: {{ GIT_DESCRIBE_NUMBER }}
    script: "{{ PYTHON }}  -m pip install . --no-deps"
    entry_points:
        - payu = payu.cli:parse
        - payu-run = payu.subcommands.run_cmd:runscript
        - payu-collate = payu.subcommands.collate_cmd:runscript
        - payu-profile = payu.subcommands.profile_cmd:runscript

source:
    git_url: ../

requirements:
    build:
        - python
        - pbr
        - setuptools
    run:
        - python
        - f90nml >=0.16
        - yamanifest >=0.3.4
        - PyYAML
        - python-dateutil
        - tenacity
        - requests
        # The following two requirements are from the security
        # extra for the pypi package
        - pyOpenSSL >=0.14
        - cryptography>=1.3.4

test:
    imports:
        - payu
    commands:
        - payu list


about:
    home: https://github.com/payu-org/payu/
