#!/bin/bash

# Testing
set -ex

PKG_NAME="payu"
PKG_VERSION=""
FORCE="y"

module purge    # Remove existing modules
rm -rf build    # Delete old scripts
unset PYTHONPATH
export PYTHONNOUSERSITE='y'

# Application name and version
if [[ ! -n ${PKG_VERSION} ]]; then
    PKG_VERSION=$(python -c "print(__import__('${PKG_NAME}').__version__)")
fi

# User information
AUTHOR_UID=$(whoami)
MOD_AUTHOR=$(getent passwd ${AUTHOR_UID} | cut -d: -f5)
MOD_EMAIL=$(ldapsearch -LLL -x "(uid=${AUTHOR_UID})" mail | \
            grep -oP "(?<=mail: ).*$")

# Module environment
PROJECT_APPS="/apps"
PROJECT_MODULEFILES="/apps/Modules/modulefiles"
#PROJECT_MODULEFILES="/apps/Modules/restricted-modulefiles/fp0"

PKG_ROOT="${PROJECT_APPS}/${PKG_NAME}/${PKG_VERSION}"
#PKG_ROOT=tmp 

# Check if application is already installed
if [[ -d ${PKG_ROOT} && ! -n ${FORCE} ]]; then
    echo "There is already an application installed at ${PKG_ROOT}."
    exit -1
fi

# Delete existing app if already installed
rm -rf ${PKG_ROOT}

# Python 3.6 install
module purge
module load python3/3.6.2
module load netcdf/4.2.1.1

PAYU_LIB=${PKG_ROOT}/lib/python3.6/site-packages

mkdir -p ${PAYU_LIB}

# cftime install is broken, used by netCDF4
# Install this one separately via pip
PYTHONPATH=${PAYU_LIB} \
    pip3 install cftime --prefix=${PKG_ROOT}

#PYTHONPATH=${PAYU_LIB} \
#    python3 setup.py install --prefix=${PKG_ROOT}
PYTHONPATH=${PAYU_LIB} \
    pip3 install -e .[mitgcm] --prefix=${PKG_ROOT}

#------------------------------------------------------------------------------
# Generate the modulefile

PKG_APP_MODS=${PROJECT_MODULEFILES}/${PKG_NAME}
mkdir -p ${PKG_APP_MODS}

PKG_MOD=${PKG_APP_MODS}/${PKG_VERSION}
printf "#%%Module1.0\n" > ${PKG_MOD}
printf "# ${PKG_NAME} ${PKG_VERSION} environment module\n" >> ${PKG_MOD}
printf "\n" >> ${PKG_MOD}
printf "set install-contact \"${MOD_AUTHOR} <${MOD_EMAIL}>\"\n" >> ${PKG_MOD}
printf "set install-date \"$(date +%Y-%m-%d)\"\n" >> ${PKG_MOD}
printf "source /opt/Modules/extensions/extensions.tcl\n" >> ${PKG_MOD}
printf "docommon\n" >> ${PKG_MOD}

## Update default version
#printf "#%%Module1.0\n" > ${PKG_APP_MODS}/.version
#printf "set ModulesVersion ${PKG_VERSION}\n" >> ${PKG_APP_MODS}/.version

# Set permissions
chmod g=rwX ${PROJECT_APPS}/${PKG_NAME}
chmod o=rX ${PROJECT_APPS}/${PKG_NAME}

chgrp -R apps ${PKG_ROOT}
chmod -R g=rwX ${PKG_ROOT}
chmod -R o=rX ${PKG_ROOT}

chmod g=rwX ${PKG_APP_MODS}
chmod o=rX ${PKG_APP_MODS}

chgrp apps ${PKG_MOD}
chmod g=rwX ${PKG_MOD}
chmod o=rX ${PKG_MOD}
