name: CD

on:
  push:
    tags:
      - '*'

env:
  PY_VERSION: 3.11

jobs:
  pypi-build:
    name: Build package for PyPI
    if: github.repository == 'payu-org/payu'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - uses: actions/setup-python@v6
        with:
          python-version: ${{ env.PY_VERSION }}

      - run: |
          python3 -m pip install --upgrade build && python3 -m build

      - uses: actions/upload-artifact@v7
        with:
          name: release
          path: dist

  pypi-publish:
    # Split build and publish to restrict trusted publishing to just this workflow
    needs: ['pypi-build']
    name: Publish to PyPI.org
    runs-on: ubuntu-latest
    permissions:
      # IMPORTANT: this permission is mandatory for trusted publishing
      id-token: write
    steps:
      - uses: actions/download-artifact@v8
        with:
          name: release
          path: dist

      - name: Publish package distributions to PyPI
        uses: pypa/gh-action-pypi-publish@cef221092ed1bacb1cc03d23a2d87d1d172e277b # v1.14.0

  conda:
    name: Build with conda and upload
    if: github.repository == 'payu-org/payu'
    runs-on: ubuntu-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Checkout source
        uses: actions/checkout@v6

      - name: Setup conda environment
        uses: conda-incubator/setup-miniconda@8ee1f361103df19b6f8c8655fd3967a8ecb162d5 # v4.0.1
        with:
          miniconda-version: "latest"
          python-version: ${{ env.PY_VERSION }}
          environment-file: conda/environment.yml
          auto-update-conda: false
          auto-activate-base: false
          show-channel-urls: true

      - name: Build and upload conda package
        uses: ACCESS-NRI/action-build-and-upload-conda-packages@v3.1.0
        with:
          meta_yaml_dir: conda
          user: accessnri
          label: main
          token: ${{ secrets.anaconda_token }}
