name: Deploy payu dev
description: |
  Deploy payu development containerised environment used by ACCESS-NRI-related workflows.

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
    deploy-access-nri-payu-dev:
        name: Deploy payu dev containerised environment
        runs-on: ubuntu-latest
        env:
          GH_TOKEN: ${{ secrets.CONTAINERISED_ENVS_INFRA_WORKFLOW_PAT }}
        steps:
          - name: Deploy
            run: |
              gh workflow run \
                --repo access-nri/containerised-environments-infra \
                --ref main \
                release_dev_env.yml \
                -f environment=payu
